name: 🪲 问题反馈
description: 报告您在使用本程序过程中遇到的问题
title: "🪲 [Bug] "
labels: ["Bug"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您抽出宝贵的时间来填写此问题报告！

  - type: checkboxes
    id: verify
    attributes:
      label: ⭕ 确认问题
      description: 请根据真实情况勾选下列选项以确认是否真的出现了问题
      options:
        - label: 我正在使用的是最新版本
          required: true
        - label: 本程序是在 GitHub 下载的，而不是在其他网站或渠道
          required: true
        - label: 我没有更改过程序的配置文件
          required: true
        - label: 我没有在程序的安装目录修改、删除了某些必要文件或更改了它们的访问权限
          required: true

  - type: textarea
    id: report
    attributes:
      label: ⭕ 问题描述
      description: 请详细说明该问题是怎样发生的
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: 🌈 [选填] 错误详情
      description: 如果弹出了错误消息框，请将其截图并粘贴到此处
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: 🌈 [选填] 可能的解决方法
      description: 请详细说明可能会解决此问题的方法，内容可以是文字描述或者是相关代码
    validations:
      required: false
